#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 20 15:26:40 2018

@author: yanglinxuan
"""

#leetcode 537
'''
Given two strings representing two complex numbers.

You need to return a string representing their multiplication. 
Note i2 = -1 according to the definition.
'''

def complexNumberMultiply(a,b):
    """
    :type a:str
    :type b:str
    :rtype:Str
    """
    a=a.split('+')
    areal=int(a[0])
    aim=int(a[1][:-1])
    b=b.split('+')
    breal=int(b[0])
    bim=int(b[1][:-1])
    print(areal,aim,breal,bim)
    
    res=str(areal*breal+aim*bim*(-1))+'+'+str(areal*bim+aim*breal)+'i'
    return res 


    
print(complexNumberMultiply('1+-1i','1+-1i'))


